/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/hongxiaoyu/Projects/FPGA/KC_LS1u_SoC/anlogic/al_ip/ASYNC_DPBRAM.v
 ** Date	:	2021 02 22
 ** TD version	:	5.0.25341
\************************************************************/

`timescale 1ns / 1ps

module ASYNC_DPBRAM ( 
	doa, dia, addra, cea, clka, wea, rsta,ocea, 
	dob, dib, addrb, ceb, clkb, web
);


	parameter DATA_WIDTH_A = 8; 
	parameter ADDR_WIDTH_A = 11;
	parameter DATA_DEPTH_A = 2048;
	parameter DATA_WIDTH_B = 8;
	parameter ADDR_WIDTH_B = 11;
	parameter DATA_DEPTH_B = 2048;
	parameter REGMODE_A    = "OUTREG";
	parameter REGMODE_B    = "NOREG";
	parameter WRITEMODE_A  = "NORMAL";
	parameter WRITEMODE_B  = "NORMAL";

	output [DATA_WIDTH_A-1:0] doa;
	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [DATA_WIDTH_B-1:0] dib;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  wea;
	input  web;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;
	input  rsta;
	input  ocea;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("DP"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(ocea),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(wea),
				.web(web),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob(dob));


endmodule