/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/hongxiaoyu/Projects/FPGA/KC_LS1u_SoC/anlogic/al_ip/dRAM.v
 ** Date	:	2021 02 28
 ** TD version	:	5.0.25341
\************************************************************/

`timescale 1ns / 1ps

module dRAM ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 32; 
	parameter ADDR_WIDTH_W = 4;
	parameter DATA_DEPTH_W = 16;
	parameter DATA_WIDTH_R = 8;
	parameter ADDR_WIDTH_R = 6;
	parameter DATA_DEPTH_R = 64;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	AL_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule