/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/hongxiaoyu/Projects/FPGA/KC_LS1u_SoC/anlogic/al_ip/pll.v
 ** Date	:	2021 02 01
 ** TD version	:	5.0.25341
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             24.000Mhz
//	Clock multiplication factor: 2
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 48.000000 MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll(refclk,
		reset,
		extlock,
		clk0_out);

	input refclk;
	input reset;
	output extlock;
	output clk0_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("24.000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN("2"),
		.ICP_CURRENT(9),
		.KVCO("2"),
		.LPF_CAPACITOR("1"),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(1),
		.FBCLK_DIV(2),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(21),
		.CLKC0_CPHASE(20),
		.CLKC0_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(extlock),
		.load_reg(1'b0),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({open, open, open, open, clk0_buf}));

endmodule
